services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: nest-redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redispassword}
    networks:
      - nest-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # MongoDB Primary Node
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - nest-network
    volumes:
      - ./volumes/mongo-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
    command: ["bash", "/docker-entrypoint-initdb.d/mongo-init.sh"]
  
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - nest-network
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    command: npm run start:dev

networks:
  nest-network:
    driver: bridge

